package game.wreckriff.config;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/** One immutable identity generated by Gradle and shared by UI, diagnostics and packaging. */
public record BuildInfo(String version,String commit,String sourceSha256) {
    private static final BuildInfo CURRENT=read();
    public static BuildInfo current() {return CURRENT;}
    private static BuildInfo read() {
        Properties properties=new Properties();
        try(InputStream input=BuildInfo.class.getResourceAsStream("/build-info.properties")) {
            if(input==null)throw new IllegalStateException("Missing generated build identity");
            properties.load(input);
        } catch(IOException exception) {throw new IllegalStateException("Cannot read generated build identity",exception);}
        return new BuildInfo(required(properties,"version"),required(properties,"commit"),required(properties,"sourceSha256"));
    }
    private static String required(Properties properties,String key) {
        String value=properties.getProperty(key);
        if(value==null||value.isBlank())throw new IllegalStateException("Missing build property: "+key);
        return value;
    }
}
