"""Offline authoring of the three original kilometre-scale campaign locations.

All dimensions are metres. Original revision 1 and its generators are preserved in
assets/campaign-layouts-revision1. No assets are downloaded or generated by builds.
"""
import json
import math
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'src/main/resources/config'
def vec(p):return dict(zip(('x','y','z'),(round(float(v),4) for v in p)))
def dist(a,b):return math.sqrt(sum((a[i]-b[i])**2 for i in range(3)))
def segment_distance(x,z,a,b):
    dx,dz=b[0]-a[0],b[2]-a[2]
    t=max(0,min(1,((x-a[0])*dx+(z-a[2])*dz)/(dx*dx+dz*dz)))
    return math.hypot(x-a[0]-dx*t,z-a[2]-dz*t)
def mesh_height_at(mesh,x,z):
    vertices=mesh['vertices']
    for start in range(0,len(mesh['indices']),3):
        a,b,c=(vertices[mesh['indices'][start+i]] for i in range(3))
        denominator=(b['z']-c['z'])*(a['x']-c['x'])+(c['x']-b['x'])*(a['z']-c['z'])
        u=((b['z']-c['z'])*(x-c['x'])+(c['x']-b['x'])*(z-c['z']))/denominator
        v=((c['z']-a['z'])*(x-c['x'])+(a['x']-c['x'])*(z-c['z']))/denominator
        if u>=-.0001 and v>=-.0001 and u+v<=1.0001:return u*a['y']+v*b['y']+(1-u-v)*c['y']
    return None

class Location:
    def __init__(self,identity,title,theme,width,depth,enemies,boss):
        self.resource='arena-'+identity.replace('_','-')
        self.data=dict(schemaVersion=3,id=identity,metadata=dict(title=title,theme=theme,normalEnemies=enemies,
            durationSeconds=0,recoveryCost=0,introduction='',music=f'audio/music/{identity}-normal.wav',bossMusic=f'audio/music/{identity}-boss.wav'),
            bounds=dict(minX=0,maxX=width,minZ=0,maxZ=depth,recoveryY=-45),boxes=[],ramps=[],spawns=[],pickups=[],hazards=[],nodes=[],edges=[],surfaces=[],
            launchPads=[],drops=[],destructibles=[],secrets=[],barriers=[],bosses=[boss],layoutRevision=2,meshes=[],districts=[])
        self.points={};self.node_ids={};self.routes=[];self.reserved=[];self.width=width;self.depth=depth
    def box(self,name,center,size,material='concrete',collision=True,yaw=0):
        self.data['boxes'].append(dict(id=name,center=vec(center),size=vec(size),material=material,collision=collision,yawDegrees=yaw));return name
    def slab(self,name,rect,y=0,material='asphalt',level=0):
        x1,x2,z1,z2=rect;self.box(name,((x1+x2)/2,y-.5,(z1+z2)/2),(x2-x1,1,z2-z1),material)
        self.data['surfaces'].append(dict(id=name,geometryId=name,level=level,grip=1));return name
    def mesh(self,name,vertices,material='concrete',level=0):
        # All indexed faces point upward; reversing the polygon preserves one canonical source.
        a,b,c=vertices[:3]
        if (b[2]-a[2])*(c[0]-a[0])-(b[0]-a[0])*(c[2]-a[2])>0:vertices=list(reversed(vertices))
        self.data['meshes'].append(dict(id=name,vertices=[vec(p) for p in vertices],indices=[0,3,2,0,2,1],material=material,collision=True))
        self.data['surfaces'].append(dict(id=name,geometryId=name,level=level,grip=1));return name
    def corridor(self,name,a,b,width=38,material='asphalt',level=1):
        dx,dz=b[0]-a[0],b[2]-a[2];length=math.hypot(dx,dz);sx,sz=dz/length*width/2,-dx/length*width/2
        return self.mesh(name,[(a[0]+sx,a[1],a[2]+sz),(b[0]+sx,b[1],b[2]+sz),(b[0]-sx,b[1],b[2]-sz),(a[0]-sx,a[1],a[2]-sz)],material,level)
    def floor_except(self,holes,material='concrete'):
        xs=sorted({0,self.width,*[v for h in holes for v in h[:2]]});zs=sorted({0,self.depth,*[v for h in holes for v in h[2:]]})
        for i in range(len(xs)-1):
            for j in range(len(zs)-1):
                x,z=(xs[i]+xs[i+1])/2,(zs[j]+zs[j+1])/2
                if not any(h[0]<x<h[1] and h[2]<z<h[3] for h in holes):self.slab(f'ground-{i}-{j}',(xs[i],xs[i+1],zs[j],zs[j+1]),0,material)
    def surface(self,p):
        candidates=[];ids={s['geometryId'] for s in self.data['surfaces']}
        for b in self.data['boxes']:
            if b['id'] not in ids:continue
            c,s=b['center'],b['size'];a=math.radians(b['yawDegrees']);dx,dz=p[0]-c['x'],p[2]-c['z']
            if abs(math.cos(a)*dx-math.sin(a)*dz)<=s['x']/2+.01 and abs(math.sin(a)*dx+math.cos(a)*dz)<=s['z']/2+.01:candidates.append((abs(p[1]-c['y']-s['y']/2),b['id']))
        for m in self.data['meshes']:
            v=m['vertices']
            for idx in range(0,len(m['indices']),3):
                a,b,c=(v[m['indices'][idx+i]] for i in range(3));den=(b['z']-c['z'])*(a['x']-c['x'])+(c['x']-b['x'])*(a['z']-c['z'])
                u=((b['z']-c['z'])*(p[0]-c['x'])+(c['x']-b['x'])*(p[2]-c['z']))/den;w=((c['z']-a['z'])*(p[0]-c['x'])+(a['x']-c['x'])*(p[2]-c['z']))/den
                if u>=-.0001 and w>=-.0001 and u+w<=1.0001:candidates.append((abs(p[1]-u*a['y']-w*b['y']-(1-u-w)*c['y']),m['id']))
        if not candidates or min(candidates)[0]>.06:raise ValueError(f'{self.data["id"]}: no surface at {p}')
        return min(candidates)[1]
    def node(self,p):
        key=tuple(round(c,3) for c in p)
        if key not in self.node_ids:
            identity=len(self.data['nodes']);self.node_ids[key]=identity
            self.data['nodes'].append(dict(id=identity,position=vec(p),surfaceId=self.surface(p)))
        return self.node_ids[key]
    def route(self,*names,width=32,clearance=100,kind='ROAD',object_id=''):
        for first,last in zip(names,names[1:]):
            a,b=self.points[first],self.points[last];self.routes.append((a,b,width));count=1 if kind=='OPENABLE' else max(1,math.ceil(dist(a,b)/65));before=self.node(a)
            for n in range(1,count+1):
                after=self.node(tuple(a[i]+(b[i]-a[i])*n/count for i in range(3)))
                self.data['edges'].append(dict(id=f'{first}-{last}-{n}',**{'from':before},to=after,width=width,clearance=clearance,type=kind,objectId=object_id,bidirectional=True));before=after
    def routes_add(self,paths,width=32):
        for path in paths:self.route(*path.split(),width=width)
    def district(self,identity,title,center,radius=320):
        ids=[n['id'] for n in self.data['nodes'] if math.hypot(n['position']['x']-center[0],n['position']['z']-center[2])<radius]
        self.data['districts'].append(dict(id=identity,title=title,center=vec(center),patrolNodeIds=ids))
    def building(self,name,rect,height,material='concrete',base=0,yaw=0):
        x1,x2,z1,z2=rect;self.box(name,((x1+x2)/2,base+height/2,(z1+z2)/2),(x2-x1,height,z2-z1),material,yaw=yaw)
    def hall(self,name,rect,height=20,material='blue',base=0,portals=None):
        x1,x2,z1,z2=rect;self.reserved.append(rect)
        for label,z in [('north',z1),('south',z2)]:
            if portals and label in portals:
                center,width=portals[label]
                for wing,lo,hi in [('west',x1,center-width/2),('east',center+width/2,x2)]:
                    self.box(f'{name}-{label}-{wing}-wall',((lo+hi)/2,base+height/2,z),(hi-lo,height,2),material)
            else:self.box(name+'-'+label+'-wall',((x1+x2)/2,base+height/2,z),(x2-x1,height,2),material)
        self.box(name+'-roof',((x1+x2)/2,base+height+1,(z1+z2)/2),(x2-x1+3,2,z2-z1+3),'steel')
        for x in (x1+3,x2-3):
            for z in (z1+3,z2-3):self.box(name+f'-column-{x}-{z}',(x,base+height/2,z),(3,height,3))
    def city_blocks(self,xs,zs,theme):
        palettes={'NEON':['dark-concrete','blue','black'],'CONSTRUCTION':['concrete','rust','blue'],'CARNIVAL':['faded-red','ivory','blue']}
        for ix,x in enumerate(xs):
            for iz,z in enumerate(zs):
                half=29 if theme=='CARNIVAL' else 38
                if any(segment_distance(x,z,a,b)<half+width/2+15 for a,b,width in self.routes):continue
                if any(r[0]-half<x<r[1]+half and r[2]-half<z<r[3]+half for r in self.reserved):continue
                try:
                    for px,pz in ((x-half,z-half),(x+half,z+half)):self.surface((px,0,pz))
                except ValueError:continue
                height={'NEON':38+(ix*19+iz*13)%88,'CONSTRUCTION':12+(ix*11+iz*7)%35,'CARNIVAL':7+(ix*3+iz*5)%12}[theme]
                self.building(f'{theme.lower()}-block-{ix}-{iz}',(x-half,x+half,z-half,z+half),height,palettes[theme][(ix+iz)%3])
    def spawn(self,names):
        for i,name in enumerate(names.split()):self.data['spawns'].append(dict(id=i,position=vec(self.points[name]),yawDegrees=90 if i%2==0 else -90))
    def supplies(self,names):
        types=['HOMING_AMMO','POWER_AMMO','MINE_AMMO','NAPALM_AMMO','BALLISTIC_AMMO','CANNON_AMMO','REPAIR','TURBO_CELL']
        for i,name in enumerate(names.split()):
            origin=self.points[name];node=self.node(origin);placed=None
            # Keep supplies away from parked spawns and ramp seams. Their approach remains on a real flat road.
            neighbors=[]
            for edge in self.data['edges']:
                if edge['type'] in ('LAUNCH','OPENABLE'):continue
                target=edge['to'] if edge['from']==node else edge['from'] if edge['to']==node else None
                if target is None:continue
                q=self.data['nodes'][target]['position'];p=(q['x'],q['y'],q['z'])
                if abs(p[1]-origin[1])<.01 and dist(origin,p)>20:neighbors.append(p)
            for offset in (14,28,40):
                for target in neighbors:
                    if dist(origin,target)<offset+5:continue
                    p=tuple(origin[k]+(target[k]-origin[k])*offset/dist(origin,target) for k in range(3))
                    others=[s['position'] for s in self.data['spawns']+self.data['pickups']]
                    if any(dist(p,(q['x'],q['y'],q['z']))<11 for q in others):continue
                    # A flat ground node is not a clear support if a crossing ramp sits just above it.
                    # Keep the socket on the visible road and preserve full vehicle headroom below high bridges.
                    if any(m['collision'] and (height:=mesh_height_at(m,p[0],p[2])) is not None and p[1]+.05<height<p[1]+5
                           for m in self.data['meshes']):continue
                    self.surface(p);placed=p;break
                if placed:break
            if placed is None:raise ValueError(f'No distinct clear supply approach: {self.data["id"]}/{name}')
            kind=types[i%8];self.data['pickups'].append(dict(id=f'supply-{i+1:02}',type=kind,position=vec(placed),respawnTicks=(40 if kind=='REPAIR' else 30 if kind=='TURBO_CELL' else 25)*120))
    def hazard(self,name,kind,p,size=(24,6,24),sector=None):
        x,y,z=p;w,h,d=size;self.data['hazards'].append(dict(id=name,type=kind,sector=sector or name,minX=x-w/2,maxX=x+w/2,minZ=z-d/2,maxZ=z+d/2,
            minY=y-.1,maxY=y+h,offTicks=1680,warningTicks=360,activeTicks=360,damageIntervalTicks=120,damage=120 if kind=='CRANE' else 90))
    def opening(self,name,a,b,material='rust',barrier=False):
        p,q=self.points[a],self.points[b];x,z=(p[0]+q[0])/2,(p[2]+q[2])/2;yaw=-math.degrees(math.atan2(q[2]-p[2],q[0]-p[0]))
        geometry=self.box(name+'-panel',(x,p[1]+2,z),(2,4,24),material,not barrier,yaw)
        if barrier:self.data['barriers'].append(dict(id=name,geometryId=geometry,sector=name,offTicks=1680,warningTicks=180,activeTicks=480))
        else:self.data['destructibles'].append(dict(id=name,geometryId=geometry,maximumHp=25))
        self.route(a,b,width=22,kind='OPENABLE',object_id=name)
    def launch(self,name,a,b,flight=2.1):
        s,t=self.points[a],self.points[b];self.data['launchPads'].append(dict(id=name,source=vec(s),target=vec(t),sourceSurfaceId=self.surface(s),landingSurfaceId=self.surface(t),
            length=12,width=12,maximumEntryAngle=55,minimumSpeed=8,compressionTicks=12,flightSeconds=flight,rearmTicks=120))
        self.data['edges'].append(dict(id=name,**{'from':self.node(s)},to=self.node(t),width=12,clearance=80,type='LAUNCH',objectId=name,bidirectional=False))
    def finish(self):
        for name,p,size in [('west',(0,6,self.depth/2),(4,12,self.depth)),('east',(self.width,6,self.depth/2),(4,12,self.depth)),
             ('south',(self.width/2,6,0),(self.width,12,4)),('north',(self.width/2,6,self.depth),(self.width,12,4))]:
            material={'CONSTRUCTION':'rust','NEON':'dark-concrete','CARNIVAL':'park-ground'}[self.data['metadata']['theme']]
            self.box('boundary-'+name,p,size,material)
        reached={0}
        while True:
            before=len(reached)
            for e in self.data['edges']:
                if e['type']=='OPENABLE':continue
                if e['from'] in reached:reached.add(e['to'])
                if e['bidirectional'] and e['to'] in reached:reached.add(e['from'])
            if len(reached)==before:break
        assert len(reached)==len(self.data['nodes']),(self.data['id'],'disconnected',set(range(len(self.data['nodes'])))-reached)
        # Validate complete drivable strips after all architecture is authored.
        # Dynamic closures are skipped; their explicit OPENABLE edges remain the owner.
        for edge in self.data['edges']:
            if edge['type'] in ('LAUNCH','OPENABLE'):continue
            first,last=(self.data['nodes'][edge[k]]['position'] for k in ('from','to'))
            a=tuple(first[k] for k in ('x','y','z'));b=tuple(last[k] for k in ('x','y','z'))
            clearance=100
            for step in range(math.ceil(dist(a,b)/3)+1):
                t=step/max(1,math.ceil(dist(a,b)/3));p=tuple(a[k]+(b[k]-a[k])*t for k in range(3))
                for box in self.data['boxes']:
                    if not box['collision']:continue
                    c,s=box['center'],box['size'];bottom,top=c['y']-s['y']/2,c['y']+s['y']/2
                    if top<=p[1]+.65:continue
                    angle=math.radians(box['yawDegrees']);dx,dz=p[0]-c['x'],p[2]-c['z']
                    if abs(math.cos(angle)*dx-math.sin(angle)*dz)>s['x']/2+2.5 or abs(math.sin(angle)*dx+math.cos(angle)*dz)>s['z']/2+2.5:continue
                    if bottom<p[1]+5:raise ValueError(f'{self.data["id"]} blocked {edge["id"]}: {box["id"]} at {p}')
                    clearance=min(clearance,bottom-p[1])
            edge['clearance']=round(clearance,3)
        (OUT/(self.resource+'.json')).write_text(json.dumps(self.data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
        print(self.data['id'],len(self.data['boxes']),'solids',len(self.data['meshes']),'meshes',len(self.data['nodes']),'nodes')

def boss(identity,name,hp,weapons,entrances,quotes,pads=()):
    return dict(id=identity,name=name,profileId=identity,maximumHp=hp,primary=weapons[0],secondary=weapons[1],
        entrances=[dict(id=i,position=vec(p),yawDegrees=90) for i,p in enumerate(entrances)],launchPadIds=list(pads),quotes=quotes)

def construction():
    a=Location('construction_17','МЕГАСТРОЙ-17','CONSTRUCTION',1600,1200,8,
        boss('boss_foreman','Бригадир',4000,('POWER','CANNON'),[(1360,0,1000),(160,0,180)],['Объект закрыт. Посторонних — под отвал','Сейчас выровняем!']))
    a.data['metadata']['introduction']='Котлован, бетонный завод и недостроенные кварталы. Пять районов одной большой стройки.'
    a.floor_except([(300,660,280,660)])
    a.slab('pit-floor',(380,580,360,580),-14,'concrete',-1)
    a.data['surfaces'][-1]['grip']=.8
    for name,vertices in [('west',[(300,0,280),(380,-14,360),(380,-14,580),(300,0,660)]),
        ('east',[(580,-14,360),(660,0,280),(660,0,660),(580,-14,580)]),
        ('south',[(300,0,280),(660,0,280),(580,-14,360),(380,-14,360)]),
        ('north',[(380,-14,580),(580,-14,580),(660,0,660),(300,0,660)])]:a.mesh('pit-'+name+'-slope',vertices)
    p={'sw':(160,0,180),'s':(760,0,180),'se':(1360,0,180),'w':(160,0,470),'nw':(160,0,1000),'n':(630,0,1000),'ne':(1360,0,1000),'e':(1360,0,560),'c':(820,0,470),
        'pit-w':(300,0,470),'pit-w-bottom':(380,-14,470),'pit':(480,-14,470),'pit-e-bottom':(580,-14,470),'pit-e':(660,0,470),
        'pit-s':(480,0,280),'pit-s-bottom':(480,-14,360),'pit-n-bottom':(480,-14,580),'pit-n':(480,0,660),
        'west-spawn':(160,0,750),'homes-nw':(390,0,900),'homes-west':(390,0,810),'homes-east':(940,0,810),'plant-west':(930,0,560),'plant-east':(1310,0,560),
        'homes-center':(665,0,810),'homes-north-door':(720,0,810),'homes-south-door':(820,0,810),'homes-north':(720,0,735),'homes-south':(820,0,895),
        'plant-center':(1120,0,560),'plant-north':(1120,0,495),'plant-south':(1120,0,630),'silo-lane-n':(1080,0,445),'silo-lane-s':(1080,0,310),
        'warehouse-center':(1100,0,180),'warehouse-north':(1100,0,255),
        'deck-ramp-west':(785,0,930),'deck-west-entry':(895,16,930),
        'warehouse-w':(950,0,180),'warehouse-e':(1250,0,180),'ramp-s':(1030,0,650),'deck-s':(1030,16,805),'deck-n':(1110,16,1055),'ramp-n':(1110,0,1160),
        'deck-west':(920,16,930),'deck-east':(1220,16,930),'gate-w':(770,0,650),'gate-e':(870,0,650),'launch-start':(920,0,745),'launch-land':(920,16,930)}
    a.points=p
    a.slab('interchange-deck',(895,1245,805,1055),16,'concrete',1)
    a.corridor('interchange-south-ramp',p['ramp-s'],p['deck-s'],42,'concrete')
    a.corridor('interchange-north-ramp',p['deck-n'],p['ramp-n'],42,'concrete')
    a.corridor('interchange-west-ramp',p['deck-ramp-west'],p['deck-west-entry'],38,'concrete')
    a.routes_add(['sw s warehouse-w warehouse-center warehouse-e se','sw w nw n ne','se e ne','w pit-w','pit-w-bottom pit pit-e-bottom',
        'pit-e c plant-west plant-center plant-east e','s pit-s','pit-s-bottom pit pit-n-bottom','pit-n homes-west homes-nw n','homes-west homes-center homes-north-door homes-south-door homes-east c s',
        'homes-east ne','c gate-e','ramp-n ne','deck-s deck-west deck-n deck-east deck-s','deck-west deck-east','c gate-w','gate-e homes-east',
        'gate-w c','gate-e ramp-s','launch-start ramp-s','homes-north-door homes-north plant-south plant-center plant-north silo-lane-n silo-lane-s warehouse-north warehouse-center',
        'homes-south-door homes-south deck-ramp-west','n deck-ramp-west','deck-west-entry deck-west','plant-south ramp-s','pit-e plant-west'])
    for first,last,obj in [('pit-w','pit-w-bottom','pit-west-slope'),('pit-e-bottom','pit-e','pit-east-slope'),('pit-s','pit-s-bottom','pit-south-slope'),
        ('pit-n-bottom','pit-n','pit-north-slope'),('ramp-s','deck-s','interchange-south-ramp'),('deck-n','ramp-n','interchange-north-ramp'),
        ('deck-ramp-west','deck-west-entry','interchange-west-ramp')]:a.route(first,last,kind='RAMP',object_id=obj)
    a.launch('construction-gantry-launch','launch-start','launch-land',3.2)
    a.opening('short-cut','gate-w','gate-e')
    a.hall('unfinished-apartments',(430,900,778,844),24,'concrete',portals={'north':(720,60),'south':(820,60)})
    for floor in (32,42,52):a.box(f'unfinished-floor-{floor}',(665,floor,810),(470,1.4,66),'concrete')
    a.hall('concrete-plant',(960,1280,525,595),29,'rust',portals={'north':(1120,64),'south':(1120,64)})
    a.hall('warehouse',(925,1275,145,215),18,'blue',portals={'south':(1100,60)})
    a.building('pit-crane-foundation',(344,366,319,341),10,'concrete',-10)
    for x in (350,360):
        for z in (325,335):a.box(f'pit-crane-leg-{x}-{z}',(x,47.5,z),(.8,95,.8),'yellow')
    for x,z in [(900,830),(1210,830),(930,1030),(1220,1030)]:a.box(f'viaduct-pier-{x}-{z}',(x,7.5,z),(5,15,5))
    for i,(x,z) in enumerate([(1040,390),(1120,390),(1200,390)]):a.building('silo-base-'+str(i),(x-17,x+17,z-17,z+17),48,'steel')
    a.hazard('crane-1','CRANE',(410,-14,395),sector='pit-crane');a.hazard('crane-2','CRANE',(1140,0,560),sector='plant-crane');a.hazard('crane-3','CRANE',(1010,16,930),sector='gantry-crane')
    a.city_blocks(range(80,1560,140),range(80,1170,140),'CONSTRUCTION')
    a.spawn('sw c warehouse-e west-spawn homes-west plant-east deck-east nw ne')
    a.supplies('s pit plant-west deck-west homes-east nw sw ramp-n warehouse-w pit-n e deck-n n warehouse-e c homes-west ramp-s pit-s plant-east se w deck-east ne pit-e')
    for args in [('pit','Котлован',(480,-14,470),290),('homes','Недостроенный квартал',(630,0,810),300),('plant','Бетонный завод',(1120,0,560),310),
        ('warehouses','Склады',(1040,0,180),350),('interchange','Строящаяся развязка',(1080,16,940),300)]:a.district(*args)
    return a

def neon():
    a=Location('neon_zero','НЕОН-РАЙОН ZERO','NEON',1800,1400,10,
        boss('boss_prefect','Префект',3400,('HOMING','MINE'),[(1600,0,200),(160,0,1200)],['В этом районе даже аварии происходят по разрешению','Ваш маршрут отменён']))
    a.data['metadata']['introduction']='Проспекты, переулки, торговые пассажи и подземный проезд под деловым центром.'
    a.floor_except([(720,1080,540,860)],'asphalt');a.slab('underpass-floor',(800,1000,540,860),-12,'asphalt',-1)
    a.mesh('underpass-west-ramp',[(720,0,540),(800,-12,540),(800,-12,860),(720,0,860)],'asphalt',-1)
    a.mesh('underpass-east-ramp',[(1000,-12,540),(1080,0,540),(1080,0,860),(1000,-12,860)],'asphalt',-1)
    a.slab('business-overpass',(790,1010,620,780),8,'concrete',1)
    p={'sw':(160,0,200),'s1':(520,0,200),'s2':(900,0,200),'se':(1600,0,200),'w1':(160,0,500),'w2':(160,0,920),'nw':(160,0,1200),
       'n1':(520,0,1200),'n2':(1100,0,1200),'ne':(1600,0,1200),'e1':(1600,0,500),'e2':(1600,0,920),'market-w':(290,0,500),'market-e':(745,0,500),
       'south-patrol':(660,0,200),'market-core':(510,0,500),'market-door':(590,0,500),'market-backdoor':(590,0,575),'homes-core':(510,0,920),
       'homes-w':(350,0,920),'homes-e':(680,0,920),'center-s':(900,0,440),'center-n':(900,0,1000),'business-s':(900,8,620),'business-n':(900,8,780),
       'market-turn':(690,0,570),'tech-turn':(1110,0,570),'tunnel-w':(720,0,700),'tunnel-wb':(800,-12,700),'tunnel':(900,-12,700),'tunnel-eb':(1000,-12,700),'tunnel-e':(1080,0,700),
       'tech-w':(1055,0,500),'tech-core':(1200,0,500),'tech-backdoor':(1200,0,600),'parking-north':(1320,0,840),'parking-core':(1320,0,920),
       'tech-e':(1525,0,500),'parking-w':(1105,0,920),'parking-e':(1535,0,920),'parking-up':(1160,12,1080),
       'parking-spawn':(1460,12,1080),'parking-up-e':(1500,12,1080),'parking-ramp':(1060,0,1080),'parking-down':(1620,0,1080),
       'express-s':(900,0,320),'express-a':(810,22,590),'express-b':(540,22,1010),'express-n':(450,0,1200),
       'market-back':(290,0,600),'alley-s':(520,0,650),'alley-n':(520,0,780),'shortcut-w':(1220,0,700),'shortcut-e':(1360,0,700)}
    a.points=p;a.slab('parking-deck',(1160,1500,1040,1135),12,'concrete',1)
    connections=[('parking-west-ramp','parking-ramp','parking-up'),('parking-east-ramp','parking-up-e','parking-down'),
        ('business-south-ramp','center-s','business-s'),('business-north-ramp','business-n','center-n'),
        ('express-south-ramp','express-s','express-a'),('express-diagonal','express-a','express-b'),('express-north-ramp','express-b','express-n')]
    for name,first,last in connections:a.corridor(name,p[first],p[last])
    a.routes_add(['sw s1 s2 se','sw w1 w2 nw n1 n2 ne','se e1 e2 ne','w1 market-w market-core market-door market-e center-s tech-w tech-core tech-e e1',
        'w2 homes-w homes-core homes-e center-n parking-w parking-core parking-e e2','s1 market-w','s2 center-s','market-e market-turn tunnel-w','tunnel-e tech-turn tech-w','homes-e tunnel-w',
        'tunnel-e parking-w','center-n n2','homes-w n1','tech-e se','parking-e ne','tunnel-wb tunnel tunnel-eb','parking-w parking-ramp','parking-up parking-up-e',
        'parking-down e2','s2 express-s','express-n n1','market-w market-back alley-s','alley-n homes-w','alley-s tunnel-w','alley-n tunnel-w',
        'tunnel-e shortcut-w','shortcut-e e1','shortcut-e e2','business-s business-n','market-door market-backdoor homes-core','homes-e parking-w',
        'tech-core tech-backdoor parking-north parking-core'])
    for obj,first,last in connections+[('underpass-west-ramp','tunnel-w','tunnel-wb'),('underpass-east-ramp','tunnel-eb','tunnel-e')]:a.route(first,last,kind='RAMP',object_id=obj,width=28)
    a.opening('city-barrier-west','alley-s','alley-n','yellow',True);a.opening('city-barrier-east','shortcut-w','shortcut-e','yellow',True)
    a.hall('shopping-passage',(325,705,468,532),24,'blue',portals={'south':(590,60)})
    a.hall('technical-complex',(1090,1490,468,532),26,'dark-concrete',portals={'south':(1200,64)})
    a.hall('parking-ground-floor',(1140,1500,886,954),22,'concrete',portals={'north':(1320,64)});a.box('parking-roof',(1330,22,1087),(360,2,98),'concrete')
    for x,y,z in [(798,10,628),(638,10,850),(536,10,980)]:
        for side in (-29,29):a.box(f'express-pier-{x}-{side}',(x+side,y,z),(5,20,5),'concrete')
    a.hazard('traffic-west','TRAFFIC',(360,0,200),(140,4,24),'traffic');a.hazard('traffic-east','TRAFFIC',(1290,0,200),(180,4,24),'traffic')
    a.hazard('electric-strip','ELECTRIC',(1200,0,500),(12,6,26))
    a.city_blocks(range(85,1760,140),range(80,1360,135),'NEON')
    a.spawn('sw market-e tech-e parking-e homes-w center-s tunnel parking-spawn nw ne south-patrol')
    a.supplies('s1 market-w center-s tech-w tunnel parking-w sw n2 e1 market-e homes-w parking-up s2 tech-e w2 parking-e alley-s shortcut-e center-n express-b n1 e2 tunnel-e homes-e express-s parking-up-e nw se ne w1 parking-down s1')
    for args in [('business','Деловой центр',(1000,0,430),400),('market','Торговые улицы',(490,0,500),310),('homes','Жилые дворы',(490,0,990),310),
        ('transport','Развязка и подземные проезды',(900,-12,700),370),('parking','Многоэтажный паркинг',(1350,0,1010),300)]:a.district(*args)
    return a

def carnival():
    a=Location('euphoria_park','ЛУНАПАРК ЭЙФОРИЯ','CARNIVAL',1500,1300,12,
        boss('boss_emcee','Конферансье',4000,('NAPALM','POWER'),[(1320,0,180),(170,0,1090)],['Билеты невозвратные. Как и вы!','А теперь — через озеро!'],['island-south-launch','island-north-launch']))
    a.data['bounds']['recoveryY']=-8
    a.data['metadata']['introduction']='Озеро с островом, аттракционы и цирк. Береговые дороги и служебные проезды встречаются у мостов.'
    a.floor_except([(500,950,440,880)],'park-ground');a.slab('lake-bottom',(500,950,440,880),-18,'dark-concrete',-1);a.slab('island',(630,820,570,760),3,'park-ground',1)
    # Finish the rise BEFORE the island footprint. The flat landing avoids even a 0.3m vertical lip under a boss nose.
    a.corridor('west-lake-bridge',(460,0,590),(590,3,631.0526),38,'steel');a.corridor('west-island-landing',(590,3,631.0526),(650,3,650),38,'steel')
    a.corridor('east-island-landing',(800,3,650),(860,3,677),36,'steel');a.corridor('east-lake-bridge',(860,3,677),(1000,0,740),36,'steel')
    a.corridor('north-island-landing',(730,3,740),(746.6667,3,800),32,'steel');a.corridor('north-lake-bridge',(746.6667,3,800),(780,0,920),32,'steel')
    a.corridor('southwest-lake-bridge',(530,0,390),(680,3,548),32,'steel');a.corridor('southwest-island-landing',(680,3,548),(720,3,590),32,'steel')
    a.corridor('northwest-island-landing',(650,3,650),(590,3,699.2857),28,'steel');a.corridor('northwest-lake-bridge',(590,3,699.2857),(370,0,880),28,'steel')
    a.box('lake-water',(725,-1.1,660),(450,.12,440),'cyan',False)
    p={'entry':(160,0,170),'entrance-mid':(280,0,170),'fair-s':(510,0,170),'show-s':(950,0,190),'se':(1320,0,180),'fair-w':(250,0,390),'fair-e':(530,0,390),
       'shore-w':(420,0,570),'bridge-w':(460,0,590),'shore-nw':(370,0,880),'circus-w':(70,0,1090),'circus-e':(600,0,1090),
       'circus-center':(350,0,1090),'circus-north':(350,0,1020),'north':(800,0,1110),'shore-n':(780,0,920),'ne':(1270,0,1090),
       'depot-north':(1220,0,890),'depot-nw':(1020,0,1050),'depot-w':(1020,0,960),'depot-core':(1220,0,960),'depot-e':(1435,0,960),
       'ridehall-back':(975,0,480),'rides-n':(1200,0,750),'rides-s':(1230,0,480),'ridehall-w':(930,0,390),'ridehall-e':(1410,0,390),'shore-e':(1000,0,740),
       'island-w':(650,3,650),'island-center':(730,3,650),'island-e':(800,3,650),'island-n':(730,3,740),'island-s':(720,3,590),'jump-s':(720,0,420),
       'bridge-west-high':(590,3,631.0526),'bridge-east-high':(860,3,677),'bridge-north-high':(746.6667,3,800),'bridge-southwest-high':(680,3,548),
       'bridge-northwest-high':(590,3,699.2857),
       'jump-s-runup':(720,0,360),'jump-n-runup':(730,0,960),
       'jump-n':(730,0,900),'gate-w':(280,0,730),'gate-e':(400,0,730),'service-s':(1400,0,580),'service-n':(1400,0,1140)}
    a.points=p
    a.routes_add(['entry entrance-mid fair-s show-s se','entrance-mid fair-e','entry fair-w fair-e show-s','fair-w shore-w shore-nw circus-w circus-center circus-e north ne',
        'fair-e shore-w','shore-w bridge-w','shore-nw shore-n north','se ridehall-e service-s service-n ne','ridehall-w ridehall-e',
        'show-s ridehall-w','ridehall-w ridehall-back rides-s rides-n depot-w depot-core depot-e service-n','rides-n shore-e','shore-n ne','rides-s service-s','depot-w depot-nw ne','depot-w north',
        'island-w island-s island-e island-n island-w','island-w island-center island-e','island-s island-center island-n',
        'shore-e depot-north depot-core','rides-n depot-north','show-s jump-s-runup jump-s','shore-n jump-n-runup jump-n','fair-w gate-w','gate-w shore-nw',
        'gate-e shore-w','gate-e shore-nw','bridge-west-high island-w','island-e bridge-east-high','island-n bridge-north-high','bridge-southwest-high island-s',
        'island-w bridge-northwest-high','shore-nw circus-north circus-center'],28)
    for first,last,obj in [('bridge-w','bridge-west-high','west-lake-bridge'),('bridge-east-high','shore-e','east-lake-bridge'),
        ('bridge-north-high','shore-n','north-lake-bridge'),('fair-e','bridge-southwest-high','southwest-lake-bridge'),
        ('bridge-northwest-high','shore-nw','northwest-lake-bridge')]:a.route(first,last,kind='RAMP',object_id=obj,width=26)
    a.launch('island-south-launch','jump-s','island-s',3.2);a.launch('island-north-launch','jump-n','island-n',3);a.opening('service-shortcut','gate-w','gate-e','faded-red')
    a.hall('circus',(145,555,1058,1122),30,'faded-red',portals={'north':(350,64)});a.hall('ride-pavilion',(975,1375,358,422),24,'purple')
    a.hall('repair-depot',(1055,1385,929,991),18,'blue',portals={'north':(1220,64)})
    a.building('ferris-foundation',(1100,1150,620,680),4,'concrete');a.building('carousel-base',(285,335,240,290),1,'faded-red')
    a.hazard('carousel','CAROUSEL',(435,0,290),(36,6,36));a.hazard('stage-fire','FIRE',(1130,0,390),(26,6,7))
    a.city_blocks(range(80,1450,115),range(70,1250,120),'CARNIVAL')
    a.spawn('entry fair-e ridehall-e depot-e circus-e shore-nw island-e rides-n ne se circus-w show-s service-s')
    a.supplies('fair-s ridehall-w shore-w island-s circus-e depot-w entry north rides-s fair-w circus-w island-e show-s ridehall-e shore-nw service-n jump-s depot-e ne island-n gate-w shore-e rides-n se shore-n service-s bridge-w fair-e jump-n circus-e depot-w north ridehall-w island-w entry shore-e fair-s circus-w service-n rides-s')
    for args in [('entrance','Входная площадь',(280,0,180),280),('fair','Ярмарка',(350,0,450),310),('lake','Озеро и остров',(730,3,650),300),
        ('rides','Большие аттракционы',(1190,0,540),340),('circus','Цирк',(350,0,1090),320),('backstage','Служебная территория',(1220,0,960),330)]:a.district(*args)
    return a

def main():
    for factory in (construction,neon,carnival):factory().finish()
    entries=[dict(id='dead-air-yard',resourceKey='arena',campaign=False)]+[dict(id=i,resourceKey='arena-'+i.replace('_','-'),campaign=True) for i in ('construction_17','neon_zero','euphoria_park')]
    (OUT/'arenas.json').write_text(json.dumps(dict(schemaVersion=1,entries=entries),indent=2)+'\n',encoding='utf-8')
    path=OUT/'arena.json';yard=json.loads(path.read_text(encoding='utf-8'));yard.update(schemaVersion=3,layoutRevision=1,meshes=[],districts=[])
    for box in yard['boxes']:box.setdefault('yawDegrees',0)
    path.write_text(json.dumps(yard,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__':main()
